# Generated by Django 5.0.7 on 2024-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_control_app', '0002_user_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
