# Generated by Django 5.0.7 on 2024-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_control_app', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Taxi', 'Taxi'), ('Food', 'Food'), ('Park', 'Park'), ('Health', 'Health'), ('Home', 'Home'), ('Park', 'Park')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3),
        ),
    ]
