# Generated by Django 5.0.7 on 2024-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_control_app', '0004_alter_transaction_account_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
