# Generated by Django 5.0.7 on 2024-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_control_app', '0006_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Taxi', 'Taxi'), ('Food', 'Food'), ('Health', 'Health'), ('Home', 'Home'), ('Park', 'Park'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
